### ISSUE TITLE
Rx.d.ts file gets into parser and results in an error when using custom `paths` in `tsconfig.json`

### ISSUE THREAD

**Issue by maximusk** [monounity/karma-typescript#250] opened 2018-02-15 15:04 UTC
When I use custom paths in the `tsconfig` I get a parsing error:

```
15 02 2018 16:57:29.709:ERROR [source-reader.karma-typescript]: Error parsing code: Unexpected token (157:7)
in D:/playground/karma-typescript-playground/node_modules/karma-typescript/examples/angular2/node_modules/rxjs/Rx.d.ts
at line 157, column 7:

... declare const operators: typeof _operators;
/**
 * ...
```

To reproduce the issue, simply [take the Angular2 example project](https://github.com/monounity/karma-typescript/tree/master/examples/angular2) and make the following changes

Add custom path mappings to `tsconfig.json`:
```
    "compilerOptions": {
       ...
        "baseUrl": ".",
        "paths": {
            "@custom/*": [
                "./node_modules/*"
            ]
        }
```

Reference the `tsconfig.json` in the `karma.conf`:

```
karmaTypescriptConfig: {
    tsconfig: './tsconfig.json',
```

And add the usage of `rxjs` into `hello.ts` component:

```
import { Subject } from "@custom/rxjs";

@Component({...})
export class HelloComponent {
    public title = "Hello :)";
    s = new Subject();
}
```

It's interesting that there's no error when the custom `paths` option is not used:
```
import { Subject } from "rxjs";
```

**Comment by maximusk** [comment] 2018-02-16 15:23
I also checked typescript module resolutions with `--traceResolution` and it resolves both `rxjs` and `@custom/rxjs` to `node_modules/karma-typescript/examples/angular2/node_modules/rxjs/Rx.d.ts` so the problem seems to be with the `karma-typescript` package itself, not the typescript

**Comment by erikbarke** [comment] 2018-02-18 09:52
I'm able to reproduce this, I'll try to come up with a fix!

**Comment by erikbarke** [comment] 2018-02-18 19:26
There's a fix in #252, does it work on your end too?

**Comment by maximusk** [comment] 2018-02-19 15:00
@erikbarke , thanks, it fixes the original issue. But, now, I have a bunch of other issues. In particular, with the `ngrx-store-freeze` package. If you use specify a custom folder outside of the `node_modules`, for example, this setup:

```
"paths": {
            "@custom/*": [
                "../../../../some/node_modules/*"
            ]
        }
```

and install ``ngrx-store-freeze` package to the `some/node_modules` and then require it from `hello.ts`, 

`import { storeFreeze } from '@custom/ngrx-store-freeze';`

you'll get an error:

> Error: Unable to resolve module [ngrx-store-freeze] from [D:/playground/karma-typescript-playground/node_modules/karma-typescript/examples/angular2/src/app/hello.js]

**Comment by erikbarke** [comment] 2018-02-19 19:26
Ok, I'll keep investigating, baby steps 😄

**Comment by erikbarke** [comment] 2018-02-19 19:54
If I ignore a bunch of typings errors like *Class 'Store<T>' incorrectly extends base class 'Observable<T>'* etc it actually works for me using a custom path like `"@custom/*": [ "../../../../some/node_modules/*" ]`... I used the latest from the master branch with the fix for this issue merged in.

**Comment by maximusk** [comment] 2018-02-20 15:57
@erikbarke , thanks, but I just fetched the latest master branch, then ran `npm i && npm run build`. Then applied the changes [in this commit](https://github.com/maximusk/karma-typescript/pull/1/commits/8a4de89952a6a6a26756d73facce9a49ba4a2b24) and ran `npm i` inside the `some` folder and inside the `examples\angular2` folder. And when I run `npm run test` inside the  `examples\angular2` I get the error I mentioned in my previous post.

**Comment by erikbarke** [comment] 2018-02-20 19:17
Are you on windows, is this a backslash issue?

**Comment by maximusk** [comment] 2018-02-20 21:06
@erikbarke,  yes,  I'm on Windows,  but I'm using git bash,  so I'm not sure it's a backslash issue. Where would I look to investigate?

**Comment by erikbarke** [comment] 2018-02-21 05:28
Probably in src/bundler/resolve/resolver.ts, `resolveFilename`. If you want to fix this in a PR, here are the [contributing guidelines](https://github.com/monounity/karma-typescript/wiki/Contributing)!

**Comment by maximusk** [comment] 2018-02-23 11:39
@erikbarke , I've explored the resolver implementation and I don't really understand how it's supposed to find the module. It's not working for `rxjs` as well. The reason is that you're using the (browser-resolve)[https://github.com/defunctzombie/node-browser-resolve] module to find the file, but it's using simple node.js resolution algorithm that looks for `node_module` folder starting from the basedir.
And so if you have a module placed inside the `node_modules` that can't be reached from the current base directory, it won't find it. And this is what happens in my case with the `ngrx-store-freeze` module. The folder `some/node_modules` can't be discovered by traversing up from the `examples\angular2` and so it fails.

If we're looking inside the `Resolver.prototype.resolveFilename` method, the parameter `bundleItem.filename` is correctly resolved to `"D:/github/karma-typescript/some/node_modules/ngrx-store-freeze/index.d.ts"`. So it would make sense to change the `basedir` for the `browser-resolve` function:

```
bopts = {
    // need different path from the `bundleItem.filename`, something like
    // basedir: require('path').dirname(bundleItem.filename),
    basedir: _this.config.karma.basePath,  
    extensions: _this.config.bundlerOptions.resolve.extensions,
    moduleDirectory: _this.config.bundlerOptions.resolve.directories,
    modules: _this.shims
};
browserResolve(moduleName, bopts, function (error2, filename2) {
```

If I apply these changes, the module is successfully resolved, and everything seems to work. Could you make these changes or I can try to make these changes myself and make a pull request?

**Comment by erikbarke** [comment] 2018-02-24 11:04
I'll take a look, thanks for investigating!

**Comment by erikbarke** [comment] 2018-02-25 05:12
Your fix + an integration test is in #256 now, my only worry is that the test works without your fix on my end...  Does my test actually capture your issue?

**Comment by erikbarke** [comment] 2018-03-03 09:11
@maximusk, is this resolved for you?

**Comment by maximusk** [comment] 2018-03-06 14:40
@erikbarke , yes, but then I encountered the behavior described in [this issue](https://github.com/monounity/karma-typescript/issues/257).

**Comment by erikbarke** [comment] 2018-03-06 19:52
Ok, closing in favor of #257!

**Closed by erikbarke** 2018-03-06 19:52 UTC
Labels: bug
