### ISSUE TITLE
Error: Cannot find module 'buffer/' from '.'

### ISSUE THREAD

**Issue by hmil** [monounity/karma-typescript#40] opened 2016-11-30 19:43 UTC
When running `npm test` in `example-project`, I get:
```
30 11 2016 11:17:53.796:ERROR [karma]: [Error: Cannot find module 'buffer/' from '.']
Error: Cannot find module 'buffer/' from '.'
    at Function.module.exports [as sync] (/Users/hadrienmilano/karma-typescript/example-project/node_modules/karma-typescript/node_modules/browser-resolve/node_modules/resolve/lib/sync.js:33:11)
    at Function.resolve.sync (/Users/hadrienmilano/karma-typescript/example-project/node_modules/karma-typescript/node_modules/browser-resolve/index.js:321:21)
    at resolveModules (/Users/hadrienmilano/karma-typescript/example-project/node_modules/karma-typescript/lib/bundlers/builtin/bundler.js:192:45)
    at appendGlobals (/Users/hadrienmilano/karma-typescript/example-project/node_modules/karma-typescript/lib/bundlers/builtin/bundler.js:116:13)
    at /Users/hadrienmilano/karma-typescript/example-project/node_modules/karma-typescript/lib/bundlers/builtin/bundler.js:75:9
    at invokeFunc (/Users/hadrienmilano/karma-typescript/example-project/node_modules/karma-typescript/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (/Users/hadrienmilano/karma-typescript/example-project/node_modules/karma-typescript/node_modules/lodash.debounce/index.js:207:14)
    at timerExpired [as _onTimeout] (/Users/hadrienmilano/karma-typescript/example-project/node_modules/karma-typescript/node_modules/lodash.debounce/index.js:195:14)
    at Timer.listOnTimeout (timers.js:92:15)
```

npm version: 2.15.9
node version: v4.5.0

I fixed this by removing the node imports from the bundler in my fork.

This bug raises the following question: Why do you provide node emulation in the browser?
If I want to test a node-specific piece of code, I'll test it in node with jasmine-node or something like that. I'll use karma only for environment agnostic and browser code, not for node code.
Thus providing node emulation seems out of scope and carries a high risk of introducing bugs because that's what emulation is known for.

Cheers

**Comment by monounity** [comment] 2016-12-01 07:11
This is probably an issue with npm, it doesn't pull in all sub dependencies for some users, I've added both browserify and its dependencies excplicitly in package.json for karma-typescript and npm still fails sometimes, I think it's the same as in #28.

I added the browserify-style node environment because users asked for it 😃

**Comment by subvertallchris** [comment] 2016-12-05 16:40
I'm also running into this using. Using yarn instead of npm over here.

**Comment by monounity** [comment] 2016-12-06 06:06
@subvertallchris, is it just the example project or your own project too?

**Comment by lufecir** [comment] 2016-12-07 11:17
I'm running into the same problem (Node: 4.4.7, NPM: 2.5.18) with my own project.

What is not really clear to me is whether there is a workaround for this or we should wait for [https://github.com/monounity/karma-typescript/issues/41] to be implemented.

**Comment by subvertallchris** [comment] 2016-12-07 14:11
I'm seeing it with my own project.

**Comment by vitalii** [comment] 2016-12-08 12:50
Can confirm, I have exactly the same error in my project.
Is there any workaround for that?

**Comment by monounity** [comment] 2016-12-08 15:23
I've tried installing this plugin on OSX, Windows 10 and Ubuntu with various versions of Node.js and npm and for the life of me I can't reproduce this error...

The fix proposed in #41, ie removing node emulation, would mean React users (among others) wouldn't be able to use the plugin, maybe this could be fixed by having a on/off switch for the node emulation stuff.

Some users have reported success installing twice with npm, and some users have installed some modules manually (and added them as dev dependencies):

```
npm install --save-dev browser-resolve
npm install --save-dev detective
npm install --save-dev buffer
npm install --save-dev process
```

I'll add a troubleshooting guide in the readme, this is affecting way too many users...

This bug is supposed to have been fixed in `npm@4.0.5`, here's to hoping!

**Comment by monounity** [comment] 2016-12-11 06:01
I've added a troubleshooting section to the documentation now, let me know if this helps solving your problem!

**Comment by lufecir** [comment] 2016-12-12 21:10
My problem is solved by upgrading to the latest node/npm. 

So now it works for me with Node 7.1.0, NPM 3.10.9 on Windows 10.

Thanks

**Comment by subvertallchris** [comment] 2016-12-12 23:35
I'm no longer using Karma, so I couldn't tell you. Thanks for the quick responses, though!

**Comment by monounity** [comment] 2016-12-13 03:38
Ok, I'm closing this, thanks guys!

**Closed by monounity** 2016-12-13 03:38 UTC
Labels: enhancement
