### ISSUE TITLE
Invalid syntax in bundle: 'import' and 'export' may only appear at the top level when importing from @angular/upgrade/static

### ISSUE THREAD

**Issue by Necroskillz** [monounity/karma-typescript#74] opened 2017-01-27 13:23 UTC
Hi, trying to use the plugin to test a hybrid app with `@angular/upgrade`, but it seems that while it uses `umd` bundles for all other angular libraries, for `@angular/upgrade/static` it just bundles the actual es6 file `static.js`

So after:

```
27 01 2017 14:16:25.992:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.1.5
27 01 2017 14:16:28.539:INFO [compiler.karma-typescript]: Compiled 71 files in 1949 ms.
27 01 2017 14:16:30.208:ERROR [karma]: Error: Invalid syntax in bundle: 'import' and 'export' may only appear at the top level (61598:0) in C:\Cygwin\tmp\karma-typescript-bundle-28484ybNCERyqRSps.js
```

I outputed the bundle to a file, and found this inside:

```
global.wrappers['C:/Devel/Source/node_modules/@angular/upgrade/static.js']=[function(require,module,exports,__dirname,__filename){ /**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
export { downgradeComponent } from './src/aot/downgrade_component';
export { downgradeInjectable } from './src/aot/downgrade_injectable';
export { UpgradeComponent } from './src/aot/upgrade_component';
export { UpgradeModule } from './src/aot/upgrade_module';

},'node_modules/@angular/upgrade/static.js',{}];
```

Not sure why this happens for `@angular/upgrade/static`, when `@angular/core/testing` works fine and does the same kind of thing (package.json in the folder point to the umd bundle).

Any idea?

**Comment by Necroskillz** [comment] 2017-01-27 13:34
Ok why it happens is that there is a folder called `static` and also file `static.js` in the `@angular/upgrade` folder. The bundle prefers the `static.js` file over going to the `static` folder to see that package.json in there redirects it to the bundle.

**Comment by erikbarke** [comment] 2017-01-27 16:04
Hey @Necroskillz, I can't reproduce this error... I added `import "@angular/upgrade"` to an integration test and the bundler chooses the umd file on OS X locally, Windows 10 in a virtual machine, on Travis CI, Appveyor. Could you take a look at 055d018 and check that I understand your problem correctly?

**Comment by Necroskillz** [comment] 2017-01-27 16:11
import { downgradeInjectable } from '@angular/upgrade/static'

**Comment by erikbarke** [comment] 2017-01-27 23:16
Ok, had a bit of a brain fart there... It seems [node-resolve](https://github.com/substack/node-resolve) doesn't resolve modules exactly the way Node.js does (`require.resolve` resolves this module correctly), so I've added rudimentary support for `aliases` to the bundler options:

```js
karmaTypescriptConfig: {
    bundlerOptions: {
        resolve: {
            alias: {
                "@angular/upgrade/static$": "../bundles/upgrade-static.umd.js"
            }
        }
    }
}
```

Does it work for you if you install from the latest dev branch, `npm install https://github.com/monounity/karma-typescript.git#2.1.8`?
If you’re behind a firewall and can’t install from GitHub, you can download the branch as a zip and install manually.

**Comment by Necroskillz** [comment] 2017-01-28 11:10
Thx for the fast response. I will try it out when im at the office next week.

**Comment by Necroskillz** [comment] 2017-01-30 11:55
Just tested and it works.

**Comment by Bjeaurn** [comment] 2017-02-15 10:15
Hi @erikbarke, I've found this thread looking for a similar problem. We're also encountering the following errors in our project:

```
15 02 2017 11:09:46.521:ERROR [karma]: Error: Invalid syntax in bundle: 'import' and 'export' may only appear at the top level (9:0) in /var/folders/8f/8t2n6rj97p598195pqb43cr40000gn/T/karma-typescript-bundle-10915oV7fGnvvLeb9.js
    at Bundler.writeBundleFile (/Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/dist/bundler.js:179:23)
    at /Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/dist/bundler.js:117:19
    at /Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/dist/bundler.js:205:17
    at onDependenciesResolved (/Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/dist/bundler.js:261:20)
    at /Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/node_modules/async/dist/async.js:936:13)
    at /Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/node_modules/async/dist/async.js:840:16
    at /Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/dist/bundler.js:326:21
    at onDependenciesResolved (/Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/dist/bundler.js:261:20)
    at /Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/node_modules/async/dist/async.js:356:16
    at eachOfArrayLike (/Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/node_modules/async/dist/async.js:929:9)
    at eachOf (/Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/node_modules/async/dist/async.js:991:5)
    at Object.eachLimit (/Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/node_modules/async/dist/async.js:3089:3)
    at Bundler.resolveDependencies (/Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/dist/bundler.js:320:19)
    at onSourceRead (/Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/dist/bundler.js:257:19)
    at /Users/joopfeenstra/projects/skg2016/node_modules/karma-typescript/dist/bundler.js:308:17
```

However we're not using any `@angular/upgrade` anywhere, as far as I know. We've also encountered this issue on our CI tool, but I've not been able to reproduce it. 

The above error was retrieved after upgrading to your suggested `2.1.8 dev` branch, to no avail. 

Is there maybe something more going on with this issue than we were led on to?

**Comment by erikbarke** [comment] 2017-02-15 10:55
Hey @Bjeaurn! If you switch off the bundler syntax validation and search for the words "import" and "export" in the bundle file (/var/folders/8f/8t2n6rj97p598195pqb43cr40000gn/T/karma-typescript-bundle-xxx.js), has any es6 modules been included?

```
karmaTypescriptConfig: {
    bundlerOptions: {
        validateSyntax: false
    }
}
```

**Comment by jfeenstra** [comment] 2017-02-15 12:02
Hi  @erikbarke, I offered the stacktrace to @Bjeaurn and followed your suggestion. The first thing I noticed was a warning: "'DEPRECATED: please replace import of `ng2-bootstrap/ng2-bootstrap` with `ng2-bootstrap`'"
This is the first thing I want to fix.

Concerning the es6 modules, is there a specific syntax you are looking for?
I see angular2 modules been mentioned (  "exports: [_angular_common.CommonModule, _angular_core.ApplicationModule") . These are ES6 modules.

**Comment by jfeenstra** [comment] 2017-02-15 13:34
Hi, Erik. After I refactored the deprecated import of ng2-bootstrap/ng2-bootstrap to ng2-bootstrap, the problem disappeared.

**Comment by erikbarke** [comment] 2017-02-15 19:11
The "Invalid syntax in bundle" error message really should be more informative, I'll try to come up with something...

**Comment by jfeenstra** [comment] 2017-02-16 07:08
Great! Thanks for your help.

**Comment by erikbarke** [comment] 2017-03-03 04:45
I'm closing this issue now, the bundle validation message has been improved and there's now support for using ES6 modules, detailed in #87.

**Closed by erikbarke** 2017-03-03 04:45 UTC
Labels: bug
