### ISSUE TITLE
karma-typescript not working with Typescript 3.2.2

### ISSUE THREAD

**Issue by KirillMetrik** [monounity/karma-typescript#308] opened 2018-12-17 19:02 UTC
### Expected behaviour
`npm test` compiles TS spec files and runs tests.

### Actual behaviour
The following error in console after starting (downgrading to Typescript below 3.2 resolves the problem).
```
17 12 2018 11:18:53.227:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.2.2
17 12 2018 11:18:57.443:ERROR [karma-server]: TypeError: Cannot read property 'kind' of undefined
    at checkNestedBlockScopedBinding (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:45885:48)
    at checkIdentifier (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:45791:13)
    at checkExpressionWorker (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:51773:28)
    at checkExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:51745:42)
    at checkNonNullExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:48096:37)
    at checkPropertyAccessExpressionOrQualifiedName (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:48129:28)
    at checkPropertyAccessExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:48122:20)
    at checkExpressionWorker (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:51802:28)
    at checkExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:51745:42)
    at checkNonNullExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:48096:37)
    at checkPropertyAccessExpressionOrQualifiedName (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:48129:28)
    at checkPropertyAccessExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:48122:20)
    at checkExpressionWorker (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:51802:28)
    at checkExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:51745:42)
    at checkNonNullExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:48096:37)
    at resolveCallExpression (C:\Radium\GitSources\flww-ui\shared-ui\src\Core.UI\node_modules\typescript\lib\typescript.js:49422:28)
npm ERR! Test failed.  See above for more details.
```

### Environment Details

- Karma version (output of `karma --version`): 3.1.3 (but also happens with earlier versions after upgrade to TypeScript 3.2.2)
- Relevant part of your `karma.config.js` file:
```
module.exports = function(config) {
    config.set({
        basePath: '../',
        frameworks: ['jasmine', 'karma-typescript'],
        preprocessors: {
            '**/*.ts': ['karma-typescript', 'coverage']
        },
        reporters: ['teamcity', 'coverage'],
        coverageReporter: {
            dir : 'coverage/',
            reporters: [
                {type: 'html', subdir: 'html'},
                {type: 'text-summary'}
            ],
            instrumenterOptions: {
                istanbul: { noCompact: true }
            }
        },
        karmaTypescriptConfig: {
            tsconfig: './tsconfig.json'
        },
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['Chrome'],
        browserNoActivityTimeout: 100000,
        browserDisconnectTimeout: 10000,
        singleRun: true
    });
};

```

### Steps to reproduce the behaviour

1. Install TypeScript 3.2.2
2. Run `npm test` for your typescript project

**Comment by erikbarke** [comment] 2018-12-17 20:10
All the unit and integration tests pass with `typescript@3.2.2`, locally on OS X, [AppVeyor (Windows)](https://ci.appveyor.com/project/monounity/karma-typescript/builds/21071455) and [Travis (Linux)](https://travis-ci.org/monounity/karma-typescript/builds/469183002) so there must something else at play here 🤔 

I just committed a small fix for making the source code for `karma-typescript` compile with `typescript@3.2.2`, which really shouldn't affect how the transpiled code behaves. Can you reproduce the issue if you install `karma-typescript` from the master branch of this repo?

**Comment by KirillMetrik** [comment] 2018-12-18 17:11
@erikbarke I have downloaded the master sources and the result is the same. Rolling back to Typescript 3.1.2 fixes the problem. Maybe it's something in Typescript?

**Comment by erikbarke** [comment] 2018-12-18 19:30
Could be, have you found anything relevant to your issue on their issue tracker?

**Comment by wbhob** [comment] 2018-12-28 14:46
Also, I'll add that the peerDependencies field of karma-typescript relies on "2", which causes warnings on NPM install. It'd be great if you could update that field to 2 || 3 or the NPM equivalent.

Thanks!

**Comment by erikbarke** [comment] 2018-12-28 21:17
@wbhob, this is fixed in 4.0.0 which is in beta on npm now ☺️

**Comment by sbkpilot1** [comment] 2019-01-03 19:13
I'm getting an incorrect peer dependency warning when running with Karma@3.1.4, peer dependencies for 3.0.13 indicate Karma@1 || 2, this hasn't been updated to Karma 3?

**Comment by sbkpilot1** [comment] 2019-01-03 19:14
@erikbarke any ETC on the 4.0.0 release?  Thanks.

**Comment by christophercr** [comment] 2019-02-05 09:02
I guess this is solved since v4.0.0 has been just released right?

**Comment by KirillMetrik** [comment] 2019-02-05 09:33
I have found this issue in Typescript repositary, might be TS problem: https://github.com/Microsoft/TypeScript/issues/28810

**Comment by erikbarke** [comment] 2019-02-05 10:52
@KirillMetrik, @christophercr, this does indeed look like a Typescript problem, closing.
(As always, feel free to reopen if it turns out it's not a Typescript bug)

**Closed by erikbarke** 2019-02-05 10:52 UTC
