### ISSUE TITLE
RangeError Maximum call stack size exceeded

### ISSUE THREAD

**Issue by joost-de-vries** [monounity/karma-typescript#25] opened 2016-11-13 08:47 UTC
I've started using `karma-typescript`. Much cleaner than using 'istanbul' directly.
But I keep hitting the following error
```
 karma start --singleRun true

13 11 2016 09:33:49.434:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.0.9
13 11 2016 09:33:53.742:INFO [compiler.karma-typescript]: Compiled 57 files in 3732 ms.
13 11 2016 09:33:57.330:ERROR [karma]: RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
    at RegExp.test (native)
    at Parser.pp.canInsertSemicolon (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:566:17)
    at Parser.pp$3.parseExprAtom (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:1775:31)
    at Parser.pp$3.parseExprSubscripts (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExprList (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOp (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:1656:43)
    at Parser.pp$3.parseExprOps (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:1639:17)
    at Parser.pp$3.parseMaybeConditional (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/joost1/source/typescript-react-redux-example/node_modules/detective/node_modules/acorn/dist/acorn.js:1597:21)
```
I'm on OS X (Darwin 16.1.0). I upgraded to node 7.1.0 but that didn't fix it.
I traced the error through `acorn` > `detective` > `module-deps` > `browserify` > `karma-typescript`. The versions of `karma-typescript` I've tried are `2.1.2` and `2.1.1`.

You can find the project [here](https://github.com/joost-de-vries/typescript-react-redux-example/tree/karma-typescript).

**Comment by monounity** [comment] 2016-11-13 09:29
Hey @joost-de-vries, I'll try to reproduce the error on my end!

**Comment by joost-de-vries** [comment] 2016-11-13 10:49
Cool.
Let me know if I can help.

**Comment by sveisvei** [comment] 2016-11-14 19:46
I did see this when including sinon@next.
Also seeing various sinon bugs when running tests via karma-typescript, those bugs does not occur when running the output from tsc via karma-browserify.

**Comment by GabiGrin** [comment] 2016-11-14 21:27
Bumped into this tool and the same is happening here too.
Got deep into adding logs to the bundler, finding that it goes crazy with readable_stream and stream_duplex requiring each other. Saw that a test + handling cyclic references was added on master. I installed from there (npm install https://github.com/monounity/karma-typescript.git) and it solved that issue. 

@monounity  Gotta ask - you would you go by writing your own bundling logic for a karma typescript plugin?

**Comment by monounity** [comment] 2016-11-15 05:02
@sveisvei, what bugs are you seeing lolex? Does it work if you use latest from master like @GabiGrin did?

@GabiGrin, if you never ask, you'll never know :) I tried using browserify the browserify way, but that would trip up the coverage remap, so I tried to use browserify in my own way and that didn't scale... The browserify code is still in the repo: https://github.com/monounity/karma-typescript/blob/master/lib/bundlers/browserify/bundler.js if you want to take a look. Right now karma-typescript uses bits and pieces of the browserify tool chain and a modified commonjs loader, but I'm more than willing to discuss taking another path if it turns out the builtin bundler doesn't cut it.

**Comment by sveisvei** [comment] 2016-11-15 07:36
@monounity I am sure its *not* karma-typescripts fault directly, it has something to do with the global namespace being decorated or something. 

From master the recursive bug was gone and all my tests are green with some selective usage of lolex.

**Comment by GabiGrin** [comment] 2016-11-15 08:05
@monounity thanks for the elaboration. I appreciate the adventurousness in reimplementing a bundler for this :)

**Comment by monounity** [comment] 2016-11-15 09:03
@GabiGrin, time will tell if this adventurousness was brave or just plain stupid, but hey, no one remembers a coward :)

**Comment by pearljamik** [comment] 2016-11-18 17:36
I am having same issue. Any comment on that ?

**Comment by monounity** [comment] 2016-11-18 18:20
@pearljamik, this bug has been fixed in 4e0081c6dc2e291ba9205fc8c6c8f4bf9468cef4 and should be published on npm this weekend. If you don't want to wait you could try the latest from master, ie `npm install https://github.com/monounity/karma-typescript`.

**Comment by monounity** [comment] 2016-11-22 06:00
@joost-de-vries, your project actually works with karma-typescript now, using the latest from master + this karma conf:

```javascript
frameworks: ['jasmine', 'karma-typescript'],

files: [
    { pattern: 'src/**/*.+(ts|tsx)' },
    { pattern: 'test-utils/**/*.ts' },
],

preprocessors: {
  '**/*.+(ts|tsx)': ['karma-typescript'],
},

karmaTypescriptConfig: {
  tsconfig: './tsconfig.json',
  compilerOptions: {
    sourceMap: true,
    inlineSourceMap: false,
  },
  include: ['**/*.ts', '**/*.tsx'],
  bundlerOptions: {
    ignoredModuleNames: [
      'react/addons',
      'react/lib/ReactContext',
      'react/lib/ExecutionEnvironment',
    ],
  },
  reports:
  {
    'html': 'coverage',
    'text-summary': '',
  },
},

reporters: ['progress', 'karma-typescript'],

browsers: ['Chrome']
```

The tests run and coverage is produced, but the support for webpack is still kind of experimental, but still, progress 😃

**Comment by joost-de-vries** [comment] 2016-11-22 23:19
@monounity super cool!
This issue can be closed then as far as I'm concerned.

**Closed** 2016-11-23 03:49 UTC
Labels: bug, enhancement
