### ISSUE TITLE
Support for typescript incremental compilation

### ISSUE THREAD

**Issue by wawyed** [monounity/karma-typescript#347] opened 2019-07-16 08:49 UTC
In typescript 3.4+ they've added support for incremental compilation which would allow subsequential compilation runs to be much faster. Is this something that could be supported by karma-typescript?

https://devblogs.microsoft.com/typescript/announcing-typescript-3-4-rc/

**Comment by erikbarke** [comment] 2019-07-19 14:55
This sounds nice! It seems an [API for incremental builds](https://github.com/microsoft/TypeScript/pull/31432) was added recently, I'll if I can squeeze this into the 5.0.0 release :relaxed:

**Comment by erikbarke** [comment] 2019-08-11 11:43
More docs:  https://www.typescriptlang.org/docs/handbook/project-references.html

**Comment by erikbarke** [comment] 2019-08-14 19:38
Update, still waiting for the API to be completed, typings are missing in `typescript@3.5.3`: https://github.com/microsoft/TypeScript/issues/29978

**Comment by erikbarke** [comment] 2019-09-13 19:30
It looks like the API is complete now, I just installed typescript@3.6.3!

**Comment by erikbarke** [comment] 2019-09-14 08:42
PR #353, for those of you interested in this feature, should this be a feature that can be toggled on/off or should the compiler just silently use the incremental API if available?

**Comment by anon-corporate** [comment] 2019-09-14 09:11
If the tsconfig has the "incremental" property set, it should just use that. 

Otherwise, I think enabling by default is fine.

**Comment by erikbarke** [comment] 2019-09-14 11:51
I've poked around the source code for `tsc`, and it performs an incremental compilation if the tsconfig option `incremental` is set, otherwise it performs the old style compilation, so I guess karma-typescript should honor the `incremental` too 🤔We should probably also support the `tsBuildInfoFile` option.

**Comment by wawyed** [comment] 2019-09-16 08:49
> 
> 
> I've poked around the source code for `tsc`, and it performs an incremental compilation if the tsconfig option `incremental` is set, otherwise it performs the old style compilation, so I guess karma-typescript should honor the `incremental` flag too 🤔We should probably also support the `tsBuildInfoFile` option.

That seems reasonable enough

**Comment by erikbarke** [comment] 2019-09-20 18:52
A bit of a dilemma: karma-typescript does all its work in-memory, ie all .ts files are compiled and served directly to Karma, no compiled versions of the .ts files are ever written to the file system, which is kind of the main selling point of this plugin, it won't touch the project structure.

On the other hand, the new incremental feature of the Typescript compiler is meant to speed up cold builds by reading information about the project graph from the last build, stored on disk.

This makes it hard to add this new feature to the karma-typescript compiler, because if the source files haven't changed (according to the `.tsbuildinfo` file), the typescript compiler outputs _nothing_ which makes the rest of the tool chain barf and crash. To fix this, the compiler could try to fall back to performing a regular compilation, but that would really defeat the purpose of the incremental feature...

Ideas?

**Comment by anon-corporate** [comment] 2019-09-22 01:53
Is the issue that you don't want to write back out to the `tsBuildInfoFile` by design or is it a limitation of the API? I can see why folks don't expect the ts output to be dumped by this plugin, but it seems reasonable that this would still modify the build-cache metadata (which is what the tsBuildInfoFile is).

**Comment by erikbarke** [comment] 2019-09-22 18:34
If karma-typescript would write to the `.tsbuildinfo` file, the graph and the file versions recorded there would correspond to what the project graph looks like when running karma, not what any .ts file compiled to .js om disk looks like, my guess is this could wreak havoc on the subsequent runs 🤔Also, even if a `.tsbuildinfo` file exists when running karma that won't help making the cold build faster because the typescript compiler produces no output if nothing has changed.

To summarize the problem: the typescript compiler relies on what the compiled version of the project looks like on disk and karma-typescript does all its work in-memory, I don't think this is going to work 😞

One way to solve this might be if karma-typescript would keep a temp cache (out of the project folder) with the transpiled .js files along with a "private" `.tsbuildinfo` but I have no idea as to what can of worms that would open (files changed in the project folder but not in the cache, weird temp file names in error messages, etc, bleh).

Also note that when running karma in watch mode, karma-typescript already mimics the `tsc` --watch mode by caching and reusing the last build program, reducing compilation time on subsequent runs, the incremental compilation feature wouldn't add any performance gains when already running karma in watch mode.

**Comment by erikbarke** [comment] 2020-03-07 12:43
Closing this since this isn't doable 😞

**Closed by erikbarke** 2020-03-07 12:43 UTC
Labels: enhancement
