### ISSUE TITLE
Config exclude and include should override not merge

### ISSUE THREAD

**Issue by cleavera** [monounity/karma-typescript#127] opened 2017-06-02 14:36 UTC
To quote your documentation:
> karmaTypescriptConfig.exclude - An array of file patterns to be excluded by the compiler. **The values will be merged with existing options.**
> Defaults to ["node_modules"].

> karmaTypescriptConfig.include - An array of file patterns to be included by the compiler. **The values will be merged with existing options.**
> This option is available in Typescript 2.0.0^.

My ts config's include and excludes currently look like this:
```json
  "include": [
    "**/*"
  ],
  "exclude": [
    "**/*.spec.ts",
    "**/node_modules/*"
  ]
```
So if i set up my karma config it would look something like this:
```js
karmaTypescriptConfig: {
  tsconfig: './tsconfig.json',
  exclude: ['**/node_modules/*']
},
```
However because the exclude and include merge rather than replace there is no way for me to get rid of the exclude `"**/*.spec.ts"`. The only way to get this behavior (as far as I can tell) is to have the separate tsconfig.

My proposal is to change this to replace rather than merge. The merge behavior can still be achieved by mimicking the previous include/excludes or something cleverer.

**Comment by erikbarke** [comment] 2017-06-03 03:17
Hey @cleavera, I'm thinking we should keep existing exclude/include functionality as to not introduce any breaking changes, but it would certainly be possible (and desirable) to augment these settings to make them merge/replace, I'll try to come up with something!

**Comment by erikbarke** [comment] 2017-07-01 05:23
Sorry for the delay, it's now possible to choose whether to merge or replace the values of the `exclude`/`include` settings. If the property is an `array` the values will be merged (so no breaking changes!) and if the property is an `object` there's an option for merging or replacing the values:

```js
  ```javascript
  {
      mode: "merge|replace",
      values: ["foo", "bar"]
  }
  ```

If you want to try it out on your end, install the latest from the development branch, `npm i github:monounity/karma-typescript#next` :smiley:
```

**Comment by cleavera** [comment] 2017-07-01 10:01
Thanks! I'll give it a bash on monday and let you know how i get on 😊

**Comment by michaelbull** [comment] 2017-07-12 21:31
I can confirm this works. My use case is as follows: I have a `setup.ts` in a shared package deployed on a private npm repository, and I want `karma-typescript` to include this file (for example `node_modules/@organization/shared/setup.ts`).

Because the default exclude is `[ 'node_modules' ]` I was wondering why I just could not get karma-typescript to import the file - as it worked in any other subdirectory. The reason was because of this default exclusion, and the ability to override this to remove said exclusion.

Would be definitely worth documenting the ability described above that facilitates replacing the exclude field entirely, or just not exclude `node_modules` by default.

**Comment by erikbarke** [comment] 2017-07-13 06:31
@michaelbull, this is documented in the readme of the [dev branch](https://github.com/monounity/karma-typescript/blob/next/README.md) under `karmaTypescriptConfig.exclude`, let me if know if something's missing!

**Closed** 2017-07-28 11:04 UTC
Labels: enhancement
