### ISSUE TITLE
 Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by Zero-man** [monounity/karma-typescript#111] opened 2017-04-05 15:52 UTC
Apologies for posting an issue that has been addressed before ([Issue #92](https://github.com/monounity/karma-typescript/issues/92)), but none of the solutions provided in the related tickets have solved the issue for me.

Here is my karma configuration file:
```
module.exports = function(config) {
    config.set({
        browsers: ['Chrome'],
        frameworks: ['mocha', 'chai', 'karma-typescript'],
        singleRun: false,
        files: [
            { pattern: 'src/**/*.ts' }
        ],
        karmaTypescriptConfig: {
            bundlerOptions: {
                transforms: [require("karma-typescript-es6-transform")()]
            },
            tsconfig: "./tsconfig.json"         
        },
        preprocessors: {
            'src/**/*.ts': ['karma-typescript']
        },
        reporters: ['mocha', 'coverage', 'karma-typescript'],
    });
};
```
Here is the tsconfig file referenced above:
```
{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "es5",
    "sourceMap": true,
    "rootDir": "./src",
    "experimentalDecorators": true,
    "types": [
      "webpack-env",
      "mocha",
      "chai"
    ],
    "typeRoots": [
      "node_modules/@types"
    ],
    "baseUrl": "./",
    "paths": {
      "*": ["node_modules/@types/*", "*"],
      "~/*": ["./src/*"]
    },
    "lib": [
      "dom",
      "es5",
      "es2015.core",
      "es2015.iterable",
      "es2015.promise"
    ]
  },
  "exclude": [
    "bin",
    "test",
    "node_modules"
  ]
}
```
And here is the error that I encounter when attempting the run the tests:
![test2](https://cloud.githubusercontent.com/assets/18588917/24713945/103b5b98-19f5-11e7-8de8-efd959ef4aad.png)

This seems to be related to the bundling step in karma-typescript -- if I rewire the karma config and use webpack as a preprocessor, the tests run fine, but obviously then I'm not getting any sweet, sweet test coverage reports. (As an aside, Webpack is used to bundle the application outside of testing). 

I'm using:
Node 6.10.2
npm 3.10.10
TS 2.2.2
karma-typescript 3.0.0
karma-typescript-es6-transform 1.0.0

Thanks for your hard work on the project -- I only wish I could get it to work!

**Comment by erikbarke** [comment] 2017-04-05 16:29
Hey @Zero-man, how is the file `src/bindings/file.js` referenced, is it imported from a Typescript file? Is the code written with ES6 syntax?

**Comment by Zero-man** [comment] 2017-04-05 18:04
It's the compiled output of `file.ts` (which is the actual file that is project getting compiled when karma runs). I also think this is the first file compiled by tsc, and the first that gets fed into the bundler (as in, it is the first of many potential errors), but I'm not really sure of that. There's an import statement at the top of the file, but no other ES6.

Sorry for being unresponsive, I'm quite swamped at the moment. Thanks for the reply!

**Comment by erikbarke** [comment] 2017-04-05 18:35
Ok, it looks like the bundler has decided not to bundle anything automatically, it checks three things before it fires:
- The `karma-commonjs` preprocessor should not be present in the config (and isn't in your config)
- The typescript compiler option `module` should be set to `commonjs` (and you have `"target": "es5"` which means it should default to module commonjs)
- The number of `import` and/or `require` statements across the project code should be greater than 0

Could you enable debug logging, `logLevel: config.LOG_DEBUG` and post the output here please?

**Comment by Zero-man** [comment] 2017-04-05 19:29
Here is the debug log:

[gvp-karma-debug.txt](https://github.com/monounity/karma-typescript/files/900579/gvp-karma-debug.txt)

I did catch this in the in the karma configuration part of the log:
`
"karmaTypescriptConfig": {
      "bundlerOptions": {
         "transforms": [
            null
         ]
      }
`

So the transforms property is null even though I have required karma-typescript-es6-transform in the config file.

**Comment by erikbarke** [comment] 2017-04-05 22:41
Thanks, I was able to reproduce this error! I've committed a few fixes, does it work for you if you install from the master branch, `npm i github:monounity/karma-typescript`?
If you’re behind a firewall and can’t install from GitHub, you can download the branch as a zip and install manually.

**Comment by Zero-man** [comment] 2017-04-05 23:08
That was quick! Unfortunately, I won't have access to the project in question until the morning, and confirming the changes on a reproduced example seems unhelpful to you -- I'll update this comment as soon as possible. Thanks very much for the help.

**Closed** 2017-04-06 19:41 UTC
Labels: bug

**Comment by rakk** [comment] 2017-04-19 10:35
My project is affected by this bug too.

Is there a release date for 3.0.1?

**Comment by erikbarke** [comment] 2017-04-19 20:10
Hey @rakk, 3.0.1 seems pretty stable so I could probably release within a few days!

**Comment by erikbarke** [comment] 2017-04-20 13:23
3.0.1 is on npm now!

**Comment by rakk** [comment] 2017-05-04 07:05
Many thanks for this release.
Cheers!
