### ISSUE TITLE
How to test a JavaScript file which is imported by it's d.ts?

### ISSUE THREAD

**Issue by ChristophAtAdlos** [monounity/karma-typescript#159] opened 2017-08-16 13:29 UTC
We have a js library inside a typescript project. For this lib, I wrote a d.ts file. The file I want test, loads the lib as follows:

`import * as lib from "../myBigJavascriptLib";`

When compiling, tsc uses the d.ts file and in the compiled code the import is transformed as follows:

`var lib = require("../html/myBigJavascriptLib.js");`

This is as expected.  

But when I use karma-typescript to test, it doesn't require the js code, but the compiled, and therefore empty d.ts code:  

```console
Chrome 60.0.3112 (Windows 10 0.0.0) ERROR
  Uncaught Error: Can't find ../myBigJavascriptLib [C:/Git/example/src/myBigJavascriptLib.d.ts] (required by C:/Git/example/src/libTest.ts)
  at node_modules/karma-typescript/src/client/commonjs.js:13
```
This is not as expected. Why, commonjs requires the d.ts file and not the js one?

I tried with
```javascript
        karmaTypescriptConfig: {
            bundlerOptions: {
                resolve: {
                    alias: {"/myBigJavascriptLib/": "./myBigJavascriptLib.js"},  // module alias
                },
```
but without success. Do I need to define bundlerOptions.transforms?  How to use it? The doc is not self explaining for me at: https://github.com/monounity/karma-typescript/blob/master/src/api/transforms.ts

Is this a bug? Any ideas how to resolve?

EDIT:  
with `resolve` and `transforms`, I didn't advance. It rewrites the imports, but in the main file (this one who imports the d.ts) the end is always as follows:

```javascript
[...]
        },
        'src/libTest.ts',
        { './myBigJavascriptLib.js': 'C:/Git/example/src/myBigJavascriptLib.d.ts' }
    ];
}(this));
```
Is this what the bundler adds...

**Comment by erikbarke** [comment] 2017-08-16 21:30
Hey @ChristophAtAdlos, could you post a small example of your lib and its typing here please?

**Comment by nros** [comment] 2017-08-17 01:33
I ran into the same problem, and this is what I found out:

## solution

To solve this problem for now, you need to use any other loader than the `karma-typescript` bundler, eg:  [karma-commonjs](https://www.npmjs.com/package/karma-commonjs).
The proper configuration is a bit tricky. The crucial part is, that **ALL** scripts imported somewhere in your source code, need to be processed with `karma-commonjs` and thus need to be listed with the *"files"-section* of karma-config. Its preprocessor adds the necessary loader function to register the loaded file with the global module registry.
```JavaScript
frameworks: ["commonjs", "detectBrowsers", "mocha", "sinon", "karma-typescript"],
preprocessors: {
             "src/**/*.ts": ["karma-typescript", "commonjs"],
             "src/**/*.js": ["commonjs", "coverage"],
             "node_modules/**/*.ts": ["karma-typescript", "commonjs"],
             "node_modules/**/*.js": ["commonjs"],
             "test/**/*.ts": ["karma-typescript", "commonjs"],
             "test/**/*.js": ["commonjs", "coverage"],
         },

        files: [
            "node_modules/YY/YY.js", // include ALL youre dependencies here
            { pattern: "src/**/*.ts" },
            { pattern: "src/**/*.js" },
            { pattern: "test/**/*.ts" },
            { pattern: "test/**/*.js" },
        ],

```

### draw back

#### UMD modules to define globals

Modules that use [UMD module scheme](https://github.com/umdjs/umd) and then are used as a global variable, do not work anymore, eg: [karma-chai](https://www.npmjs.com/package/karma-chai). Due to the `karma-commonjs` wrapper added to the file `chai.js`, the global variable is not being set upon loading the file. Hence the bundled file `node_modules/chai/adapter.js` fails with exception, not finding `window.chai`. I think this is OK, because a module loader should help to avoid cluttering the global name space. To me, the problem is with `adapter.js`.

Anyway, to overcome this error, you need to get rid of the `karma-chai` plug-in and instead include the file directly with karma config. All files listed in section `files` will benefit from the `karma-commonjs` loader and will be known to it - all other files won't.
```JavaScript
        files: [
            "node_modules/chai/chai.js",
            { pattern: "src/**/*.ts" },
            { pattern: "src/**/*.js" },
            { pattern: "test/**/*.ts" },
            { pattern: "test/**/*.js" },
        ],
```
Now you may import the [`chai`](http://chaijs.com/) assertion library directly into your TypeScript file and use it accordingly. (Note: use the fully bundled, distributable file, otherwise you would need to include every single dependency in the karma-config)
```TypeScript
import { expect }                                 from "chai/chai";
```

#### coverage

Because all `.js` files can not be processed by `karma-typescript`, you'll end up with different coverage reports that need to be merged (see #158 ). Or only default `karma-coverage` is used, then the support for TypeScript is not existing :(


## some problems I found

* The ".js" file is being loaded - because of the `include` karma-settings - but it lacks the loader to register a factory function with `global.wrappers`. Thus it is unknown to the bundler on the browser side!
```JavaScript
files: [
            { pattern: "src/**/*.ts" },
            { pattern: "src/**/*.js" },
            { pattern: "test/**/*.ts" },
            { pattern: "test/**/*.js" },
        ],
```
* you need to pre-process and compile `.js` files with `karma-typescript`, to make it known to the bundler.
```JavaScript
       karmaTypescriptConfig: {
            compilerOptions: _.extend({}, defaultTSConfig, {
                allowJs: true,
                module: "commonjs",
            }),

            include: [
                "src/**/*.js",
                "test/**/*.js",
                "src/**/*.ts",
                "test/**/*.ts",
            ],

            exclude: [
                "node_modules/**/*.js",
            ],
        },
        preprocessors: {
            "src/**/*.ts": ["karma-typescript"],
            "src/**/*.ts": ["karma-typescript"],
            "test/**/*.js": ["karma-typescript"],
            "test/**/*.js": ["karma-typescript"],
        },
```
But than I run into errors with UMD/legacy/external modules.
```JavaScript
error TS2304: Cannot find name 'define'.
```
Because TypeScript compiler is very strict, there is no solution to run `.js` files through this path.

* it is not possible to use the `karma-typescript` bundler with any other loader, eg: [SystemJS](https://www.npmjs.com/package/karma-systemjs). Although the karma config is checked against [commonjs](https://www.npmjs.com/package/commonjs) only, the bundler does support a fallback to any other existing loader. This could be achieved with something like:
```JavaScript
diff --git a/src/client/commonjs.js b/src/client/commonjs.js
index cbae2b0..8331bd6 100644
--- a/src/client/commonjs.js
+++ b/src/client/commonjs.js
@@ -4,7 +4,7 @@
     var fn = 0,
         id = 1,
         map = 2;
-    function require(filename, requiring, required) {
+    function myRequire(filename, requiring, required) {
         var wrapper,
             module = global.__karmaTypescriptModules__ [filename];
         if (!module) {
@@ -15,7 +15,35 @@
             module = { exports: {}, id: wrapper[id], uri: filename };
             global.__karmaTypescriptModules__ [filename] = module;
             wrapper[fn].call(module.exports, function (dependency) {
-                return require(wrapper[map][dependency], filename, dependency);
+                try {
+                    return myRequire(wrapper[map][dependency], filename, dependency);
+                }
+                catch(e) {
+                    dependency = "" + dependency;
+
+                    // convert relative file paths to absolute paths
+                    if (dependency[0] === "." && filename) {
+                        dependency = filename.slice(0, filename.lastIndexOf("/")) + "/" + dependency;
+
+                        dependency = dependency.replace(/\/\/+/g, "/");
+                        while(/\/[^/]+\/\.\.?\//.test(dependency)) {
+                            dependency = dependency.replace(/\/[^/]+\/\.\.?\//g, "/");
+                        }
+                    }
+
+                    if (!/\.js$/.test(dependency)) {
+                        dependency += ".js";
+                    }
+
+                    // fall back to any global loader
+                    if (typeof require === "function") {
+                        return require(dependency);
+                    }
+                    else if (SystemJS) {
+                        return SystemJS.amdRequire(dependency)
+                    }
+                    throw e;
+                }
             }, module, module.exports, filename.slice(0, filename.lastIndexOf("/")), filename);
             if(module.exports && !module.exports.default && isExtensible(module.exports)) {
                 Object.defineProperty(module.exports, "default", {
@@ -29,6 +57,6 @@
         return (typeof obj === "function" || typeof obj === "object") && Object.isExtensible(obj);
     }
     (global.entrypointFilenames || []).forEach(function(filename) {
-        require(filename, "commonjs.js", "entrypoint");
+        myRequire(filename, "commonjs.js", "entrypoint");
     });
 })(this);
```
## wish list

It would be much easier to rely on the `karma-typescript` bundler to handle everything.  To make it work, it seems as if the following is needed:

* make the bundler use another loader as a fallback
* maybe skip the TypeScript compiler and add JavaScript files directly to the bundle. Is there a pipeline to make something like `karma-bable` transpile the JS first?

**Comment by ChristophAtAdlos** [comment] 2017-08-17 08:31
@erikbarke see the abstract project at [karma-ts-test-by-dts-file](https://github.com/ChristophAtAdlos/karma-ts-test-by-dts-file)

**Comment by erikbarke** [comment] 2017-08-17 21:54
@ChristophAtAdlos, I've added support for automatically resolving `.d.ts` files to corresponding `.js` files, if you want to try it out you can install from the development branch, `npm i github:monounity/karma-typescript#next`.

These are the relevant changes I've made to your test repo:
Karma.conf.js:
```js
module.exports = function(config) {
    config.set({

        files: [
            { pattern: "src/**/*.+(js|ts)" },
        ],

        frameworks: ["qunit", "karma-typescript"],

        preprocessors: {
            "src/**/*.+(js|ts)": ["karma-typescript"],
        },

        reporters: ["progress", "karma-typescript"],

        karmaTypescriptConfig: {
            tsconfig: "./tsconfig.json",
        },

        autoWatch: true,
        browsers: ["Chrome"],
    });
};
```

```js
{
  "compilerOptions": {
    ...
    "allowJs": true, // changed
    ...
  },
  "include": [
    "src/**/*.js", // added
    "src/**/*.ts"
  ],
   ...
}
```

With this config and karma-typescript#next, `karma start` runs without errors in your test repo and both `.ts`and `.js` files get code coverage 😃

**Comment by erikbarke** [comment] 2017-08-17 21:55
@nros, would this solve your issue too? With a custom typing for `define`?

**Comment by ChristophAtAdlos** [comment] 2017-08-21 09:18
Thank you, it works well for me.

**Closed** 2017-08-22 04:32 UTC
Labels: enhancement

**Comment by ChristophAtAdlos** [comment] 2017-08-31 07:46
Do you have a plan when 3.0.6 will be released?

**Comment by erikbarke** [comment] 2017-08-31 08:08
In few days hopefully, there are still a couple of issues that need to be tested/confirmed before publishing [3.0.6](https://github.com/monounity/karma-typescript/milestone/20)!

**Comment by ChristophAtAdlos** [comment] 2017-08-31 09:01
Thank you!

**Comment by erikbarke** [comment] 2017-09-18 19:06
3.0.6 is on npm now 🚀
