### ISSUE TITLE
Branch coverage with namespaces in AngularJS

### ISSUE THREAD

**Issue by juri33** [monounity/karma-typescript#103] opened 2017-03-20 10:56 UTC
![namespace](https://cloud.githubusercontent.com/assets/12385112/24096929/f8f378be-0d63-11e7-9caa-5e81d390b951.JPG)

50% Branch Coverage? What is wrong?

**Comment by erikbarke** [comment] 2017-03-20 18:41
Hey @juri33, I'll take a look!

**Comment by erikbarke** [comment] 2017-03-20 20:18
I put your example in a file, `test.ts`:

```javascript
namespace app.trends {
    "use strict";

    angular
        .module("app.trends", []);
}
``` 

 And then tried creating coverage in two ways:

1: Running `tsc`, `istanbul` and `remap-istanbul` on the command line:
```bash
./node_modules/.bin/tsc -sourceMap test.ts
./node_modules/.bin/istanbul cover test.js
./node_modules/.bin/remap-istanbul -i coverage/coverage.json -o html-report -t html
```

2: Putting the file in the src folder of [the angularjs example project](https://github.com/monounity/karma-typescript/tree/master/examples/angularjs) and running it.

I got 100% coverage both times:
<img width="587" alt="" src="https://cloud.githubusercontent.com/assets/5539280/24119624/2ed8cce2-0db2-11e7-8e30-bbb972eb92b6.png">

So there must be something else at play here, what does the rest of your code look like, are there any files in the same namespace that aren't fully covered?

**Comment by juri33** [comment] 2017-03-21 07:15
@erikbarke appriciated
Hmm, this is strange. In the same folder is a service with the same namespace
![trends2](https://cloud.githubusercontent.com/assets/12385112/24136255/33a8773e-0e0e-11e7-8102-fd7fffa8832d.JPG)

**Comment by erikbarke** [comment] 2017-03-21 21:27
If I add another file that looks similar to your screenshot I don't get full coverage since I don't have a test that executes anything:

```js
namespace app.trends {
    "use strict";

    export interface ITrendService {
        get(id: number);
    }

    export class TrendService implements ITrendService {

        constructor(private $http: angular.IHttpService) {}

        public get(id: number) {
            return this.$http.get("/trends/" + id).then((response) => response.data);
        }
    }

    angular
        .module("app.trends")
        .service("TrendService", TrendService);
}
```
<img width="687" src="https://cloud.githubusercontent.com/assets/5539280/24171600/71fde808-0e85-11e7-8599-a9623e0225c2.png">

But I don't get that 50% branch coverage, what does your spec file look like?

**Comment by juri33** [comment] 2017-03-22 07:01
The testfile looks like this

```
/// <reference path="../../app/trends/trends.service.ts" />

describe("In the file trends.service.ts", () => {

  let MockTrendService: app.trends.ITrendsService;
  let $httpBackend: angular.IHttpBackendService;
  let API: angular.IModule;

  beforeEach(() => angular.mock.module("app"));

  beforeEach(() => {
    inject(function ($injector, _$rootScope_, TrendsService) {
      API = $injector.get("API");
      $httpBackend = $injector.get("$httpBackend");

      MockTrendService = TrendsService;
      $httpBackend.whenGET("api/langs/en.json").respond(200);
...
      $httpBackend.flush();
    });
  });

  afterEach(function () {
    $httpBackend.verifyNoOutstandingExpectation();
    $httpBackend.verifyNoOutstandingRequest();
  });

  it("the service should be defined", () => {
    expect(MockTrendService).toBeDefined();
    expect(MockTrendService).not.toBeNull();
  });
...
```

**Comment by erikbarke** [comment] 2017-03-22 21:05
I've managed to reproduce the 50% coverage now and I think understand what's happening:

This Typescript code:
```js
namespace app.trends {
    "use strict";
    angular
        .module("app.trends", []);
}
```

Gets compiled to:
```js
var app;
(function (app) {
    var trends;
    (function (trends) {
        "use strict";
        angular
            .module("app.trends", []);
    })(trends = app.trends || (app.trends = {}));
})(app || (app = {}));
```

My guess is that `app || (app = {})` only gets executed once, which means only one of the two paths are executed, which gives you 50% remapped coverage on that namespace statement... This means that Istanbul works as intended, so I'm closing this issue now 😞

**Closed by erikbarke** 2017-03-22 21:05 UTC

**Comment by juri33** [comment] 2017-03-23 12:49
@erikbarke Ok, that makes sense. But how can this be solved?  not to use namespaces?

**Comment by erikbarke** [comment] 2017-03-23 15:29
Yeah, I would go with modules instead of namespaces, as suggested in the last paragraph on this page: https://basarat.gitbooks.io/typescript/content/docs/project/namespaces.html
