### ISSUE TITLE
Error during angular typings import

### ISSUE THREAD

**Issue by NickTsitlakidis** [monounity/karma-typescript#33] opened 2016-11-19 13:57 UTC
Hello,

Great project. It eliminates messing around with karma, webpack etc. Thanks.

I'm having an issue with tests for angular. I'm using @types/angular for typing declarations and I'm trying to import them in my code using the following : 
`import * as angular from 'angular'`

But I'm getting an error that the angular module cannot be found from a directory.

This is my tsconfig compiler options which I added in karmaTypescriptConfig.tsconfig

```
"compilerOptions": {
        "target":"es5",
        "declaration": false,
        "noEmitOnError": true,
        "emitDecoratorMetadata":true,
        "experimentalDecorators":true,
        "sourceMap":true,
        "module":"commonjs",
        "moduleResolution": "node",
        "typeRoots": ["./node_modules/@types"]
    }
```

Thoughts on whats going wrong maybe?

**Comment by monounity** [comment] 2016-11-20 05:42
Hey @NickTsitlakidis, that import should work, I just verified it on an angular project using the latest version of karma-typescript. Could you update to the latest karma-typescript version and enable debug logging in Karma? That will give you the exact Karma configuration/Typescript compiler options used for the test run, which files are loaded etc.

**Comment by NickTsitlakidis** [comment] 2016-11-20 12:19
Updated to 2.1.3.

Debug logging shows that the compiler can find and read types for restangular, jasmine, etc. But it cant find for the angular types (also it cant find the lodash types). I have these inside node_modules/@types so it shouldn't be an issue right? The difference with these two is that they require the import statement in the files, unlike jasmine for example which doesn't require an import in your code.

**Comment by monounity** [comment] 2016-11-20 19:23
The project I used to verify uses `compilerOptions.types` instead of `compilerOptions.typeRoots`, ie
```json
"types": [
    "jasmine",
    "angular",
    "angular-mocks"
]
```
Does that work for you?

I'll give it another shot reproducing the error on my end!

**Comment by NickTsitlakidis** [comment] 2016-11-21 21:50
Unfortunately no. Angular is still not picked by the compiler. I'm wondering if the types I'm having are weird. Trying to make it work with 1.5.20 for the angular types.

Weirdly, angular-mocks is working.

**Comment by monounity** [comment] 2016-11-21 23:57
@NickTsitlakidis, this is indeed weird and I still can't reproduce the error... I've added a runnable example project for AngularJS: https://github.com/monounity/karma-typescript/tree/master/example-project@angularjs, hope that helps!

**Comment by NickTsitlakidis** [comment] 2016-11-22 07:41
In your example, angular is installed through npm. In my project we currently use bower for the installation. I suppose this would not affect the compiling process since the compiler only looks for typings.

**Comment by monounity** [comment] 2016-11-22 20:27
It shouldn't make any difference as long as the modules pulled in by bower end up in node_modules, but then again, the npm and bower versions of these modules could differ.

**Comment by NickTsitlakidis** [comment] 2016-11-22 21:28
So, to summarize, your example also works great here when I download it. It seems that I have no differences in versions or the typings setup in my project but it still can't find angular. I'll investigate more. Thanks anyway.

**Comment by monounity** [comment] 2016-11-24 19:34
Ok @NickTsitlakidis, I'm closing this!

**Closed** 2016-11-24 19:34 UTC
Labels: enhancement, question
