### ISSUE TITLE
TypeError: Data must be a string or a buffer

### ISSUE THREAD

**Issue by Duskfall** [monounity/karma-typescript#35] opened 2016-11-21 16:09 UTC
Hi again!
From version >= 2.1.0 when the karma is running there is the following error

````

21 11 2016 17:56:13.303:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.0.3
21 11 2016 17:56:15.674:INFO [compiler.karma-typescript]: Compiled 70 files in 1785 ms.
21 11 2016 17:56:16.115:ERROR [karma]: TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at sha1 (projectpath\node_modules\karma\lib\preprocessor.js:11:8)
    at nextPreprocessor (projectpath\node_modules\karma\lib\preprocessor.js:32:18)
    at instrumentSource (projectpath\node_modules\karma-typescript\lib\preprocessor.js:100:13)
    at Object.callback (projectpath\node_modules\karma-typescript\lib\preprocessor.js:145:21)
    at projectpath\node_modules\karma-typescript\lib\compiler.js:74:20
    at Array.forEach (native)
    at projectpath\node_modules\karma-typescript\lib\compiler.js:64:19
    at invokeFunc (projectpath\node_modules\lodash.debounce\index.js:160:19)
    at trailingEdge (projectpath\node_modules\lodash.debounce\index.js:207:14)
    at Timeout.timerExpired [as _onTimeout] (projectpath\node_modules\lodash.debounce\index.js:195:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
````

karma.conf.js:

````
module.exports = function (config) {
    config.set({
        basePath: './',
        files: [
            './node_modules/angular/angular.min.js',
            './node_modules/angular-mocks/angular-mocks.js',
            './Scripts/**/**.ts',
            './Scripts/Messages/**.ts',
            './Scripts/UnitTests/Tests/Controllers/**.ts',
            './Scripts/UnitTests/Tests/Services/**.ts'
        ],
        exclude: [],
        frameworks: [
            "jasmine", "karma-typescript"
        ],
        reporters: ['progress', 'kjhtml', "karma-typescript"],
        karmaTypescriptConfig: {
            tsconfig: './tsconfig.json', // *obligatory
            compilerOptions: {
                sourceMap: true,
                inlineSourceMap: false
            },
            /* Report type options passed to remap-istanbul */
            reports:
            {
                "html": "coverage",
                "teamcity": "coverage",
            },
            /* Options passed to remap-istanbul */
            remapOptions:
            {
                // Regex or string for excluding files, the example below is default
                //exclude: /\.(spec|test)\.ts/,
                exclude: /(typings|UnitTests|Interfaces|Libs|Messages|Models|Filters|Enum|Directives|Repositories)/,
                // Function for warning messages, these warnings are silent by default
                warn: function (message) { }
            }
        },
        preprocessors: {
            "**/*.ts": ["karma-typescript"]
        },
        browsers: ['Chrome'],
        autoWatch: true,
        singleRun: false,
        colors: true,
    });
};
````

**Comment by monounity** [comment] 2016-11-21 21:39
Hi again @Duskfall! It's easy to reproduce this bug, but I don't what's causing it. I've added lots of error debug logging, could you try the latest from master (ie `npm install https://github.com/monounity/karma-typescript`) with debug logging in Karma and post the result here?

**Comment by Duskfall** [comment] 2016-11-22 08:35
I think I found the problem.
This was happening because I didn't have `"moduleResolution": "node"` in tsconfig file. The result was that typescript was resolving the files but couldn't find a certain file which had wrong nodejs path when importing it.

Example:

`import ConfigurationService from "Services/ConfigurationService";`
Correct path after defining the module resolution rule:

`import ConfigurationService from "../Services/ConfigurationService";`

Tested with both master and 2.1.3 and it works as expected!

**Comment by monounity** [comment] 2016-11-22 20:30
Great, nice catch! I did find a bug thanks to this issue, using moduleResolution in karmaTypescriptConfig.compilerOptions doesn't work, so thanks!

**Comment by Bjeaurn** [comment] 2016-11-23 10:08
Hey @monounity, I've been running into the same exact error. I've turned on the `logLevel: config.LOG_DEBUG` and gotten the following:

```
23 11 2016 11:02:53.618:ERROR [karma]: TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:67:16)
    at sha1 (/Development/project-1/node_modules/karma/lib/preprocessor.js:11:8)
    at nextPreprocessor (/Development/project-1/node_modules/karma/lib/preprocessor.js:32:18)
    at instrumentSource (/Development/project-1/node_modules/karma-typescript/lib/preprocessor.js:148:17)
    at /Development/project-1/node_modules/karma-typescript/lib/preprocessor.js:126:21
    at Bundler.bundle (/Development/project-1/node_modules/karma-typescript/lib/bundlers/builtin/bundler.js:67:13)
    at Object.callback (/Development/project-1/node_modules/karma-typescript/lib/preprocessor.js:122:25)
    at /Development/project-1/node_modules/karma-typescript/lib/compiler.js:76:20
    at Array.forEach (native)
    at /Development/project-1/node_modules/karma-typescript/lib/compiler.js:66:19
    at invokeFunc (/Development/project-1/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (/Development/project-1/node_modules/lodash.debounce/index.js:207:14)
    at Timeout.timerExpired [as _onTimeout] (/Development/project-1/node_modules/lodash.debounce/index.js:195:14)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
23 11 2016 11:02:53.633:DEBUG [launcher]: Disconnecting all browsers
npm ERR! Test failed.  See above for more details.

```

I've found one more line inside the huge debug log that threw an error:
`23 11 2016 11:02:45.004:ERROR [compiler.karma-typescript]: No source found for /Development/project-1/target/web/node-modules/main/webjars/rxjs/add/observable/throw.d.ts`

We're running an Angular2 project including RxJS and I'm not quite sure if it's configuration or something's actually broken.

The `karma.conf.js` is as follows:

```
module.exports = function (config) {
  config.set({

    frameworks: ["jasmine", "karma-typescript"],
    logLevel: config.LOG_DEBUG,

    files: [
      {pattern: "node_modules/reflect-metadata/Reflect.js"},
      {pattern: "node_modules/zone.js/dist/zone.js"},
      {pattern: "node_modules/zone.js/dist/long-stack-trace-zone.js"},
      {pattern: "node_modules/zone.js/dist/proxy.js"},
      {pattern: "node_modules/zone.js/dist/sync-test.js"},
      {pattern: "node_modules/zone.js/dist/jasmine-patch.js"},
      {pattern: "node_modules/zone.js/dist/async-test.js"},
      {pattern: "node_modules/zone.js/dist/fake-async-test.js"},
      {pattern: "node_modules/rxjs/Rx.js" },
      {pattern: "app/assets/**/*.ts"}
    ],

    exclude: [
      "node_modules",
      "target/node-modules/webjars/",
      "node-modules"
    ],


    preprocessors: {
      "app/assets/**/*.ts": ["karma-typescript"]
    },


    reporters: ["progress", "karma-typescript"],

    karmaTypescriptConfig: {
      tsconfig: './tsconfig.json',
      compilerOptions: {
        sourceMap: true,
        inlineSourceMap: false,
      },
      reports: {
        'html': 'coverage',
        'text-summary': '',
      },
    },

    browsers: ["Chrome"]
  });
};
```

**Comment by monounity** [comment] 2016-11-23 20:20
Hey @Bjeaurn, try using the latest from main: `npm install https://github.com/monounity/karma-typescript`.

This could/should/would fix `No source found for ...` and `Data must be a string or a buffer ...`, which I think is caused by `import`ing the rxjs module.

Also, `{pattern: "node_modules/rxjs/Rx.js" }` will crash the test run, so you can remove that line, rxjs will be bundled automatically if you `import`it somewhere in your code!

**Comment by Bjeaurn** [comment] 2016-11-23 20:54
After removing the `pattern` and updating to the latest from main, I don't get the error halfway during the compilation anymore. Neatly says `Compiled 98 files in 8000ms`.

Still getting the same error:

```
23 11 2016 21:53:42.592:ERROR [karma]: TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:67:16)
    at sha1 (/Development/skg-online/node_modules/karma/lib/preprocessor.js:11:8)
    at nextPreprocessor (/Development/skg-online/node_modules/karma/lib/preprocessor.js:32:18)
    at instrumentSource (/Development/skg-online/node_modules/karma-typescript/lib/preprocessor.js:148:17)
    at /Development/skg-online/node_modules/karma-typescript/lib/preprocessor.js:126:21
    at Bundler.bundle (/Development/skg-online/node_modules/karma-typescript/lib/bundlers/builtin/bundler.js:67:13)
    at Object.callback (/Development/skg-online/node_modules/karma-typescript/lib/preprocessor.js:122:25)
    at /Development/skg-online/node_modules/karma-typescript/lib/compiler.js:76:20
    at Array.forEach (native)
    at /Development/skg-online/node_modules/karma-typescript/lib/compiler.js:66:19
    at invokeFunc (/Development/skg-online/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (/Development/skg-online/node_modules/lodash.debounce/index.js:207:14)
    at Timeout.timerExpired [as _onTimeout] (/Development/skg-online/node_modules/lodash.debounce/index.js:195:14)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
23 11 2016 21:53:42.607:DEBUG [launcher]: Disconnecting all browsers
npm ERR! Test failed.  See above for more details.

```

**Comment by monounity** [comment] 2016-11-24 06:06
@Bjeaurn, thanks 🎉

I've narrowed it down and added extra error handling, could you try running your project with the latest from main again?

**Comment by Bjeaurn** [comment] 2016-11-24 06:42
Seems to be getting there. 

```
24 11 2016 07:39:12.216:ERROR [karma]: Error: Expected a string, but got [object Undefined] for /Development/project-1/app/assets/app/incasso/importeren/incasso.response.d.ts
emitOutput: {
   "requiredModules": []
}
    at assert (/Development/project-1/node_modules/karma-typescript/lib/preprocessor.js:167:19)
    at /Development/project-1/node_modules/karma-typescript/lib/preprocessor.js:150:21
```

I'll have a look at what the `requiredModules[]` and `[object Undefined]` could be in your plugin in the meanwhile.

Or do you directly know what may be causing it?

I've looked at the file that seems to be throwing the error and it doesn't have any imports. After adding a random one (`import {Observable} from 'rxjs/Observable'`), but that didn't help.

**Comment by Bjeaurn** [comment] 2016-11-24 06:56
After some quick and dirty "logging" inside your Preprocessor.js, it seems that there's an `undefined` `bundler` as the result of your `bundler.bundle()` function.

I'm still looking at what may be causing this, so I'll report back if I find anything.

**Comment by Bjeaurn** [comment] 2016-11-24 11:41
@monounity I've done some more digging. This is what I'm at right now.

The problem seems to occur with a self created <name>.d.ts which only includes types and classes to be used throughout the application. 

When I look at `compiler.deferredCompile()` I see that there's a thing undefined in the `callback()`

```
queued.callback({
                outputText: compiledFiles[queued.file.path],
                sourceMapText: compiledFiles[queued.file.path + ".map"],
                requiredModules: cachedItem.requiredModules
            });

```

It seems there's no `compiledFiles[queued.file.path + ".map"]` for the .d.ts file.

Here's the logging for the `queued.file`:

```
{ path: '/Development/project-1/app/assets/app/incasso/importeren/incasso.response.d.js',
  originalPath: '/Development/project-1/app/assets/app/incasso/importeren/incasso.response.d.ts',
  contentPath: '/Development/project-1/app/assets/app/incasso/importeren/incasso.response.d.ts',
  mtime: 2016-11-24T11:27:05.000Z,
  isUrl: false,
  doNotCache: false }
```

The `compiledFiles[queued.file.path]` for this reference seems to return `undefined`.

**Comment by monounity** [comment] 2016-11-24 21:06
Awesome @Bjeaurn! Your efforts pushed me in the right direction and I was finally able to figure it out...

This check in the preprocessor probably returns `false` for you:

```javascript
function shouldAddLoader() {

    return compiler.getModuleFormat().toLowerCase() === "commonjs" &&
           compiler.getRequiredModulesCount() > 0 &&
           !hasPreprocessor("commonjs");
}
```
I'm guessing you're not using `module: "commonjs"`?

This made the bundler just return the source (which correctly is `undefined` for typings files) and Karma barfs if the `done`method is called with anything else than a string.

The solution is don't bundle typings files, just pass a non-empty string to Karma 🎉

So simple it's a bit embarrassing...

**Comment by Bjeaurn** [comment] 2016-11-24 21:17
Hey @monounity! Thanks for the quick responses mate! Your fix seems to have solved the original issue. 🎉

I've run into another one, but this seems to be on a whole different level. It seems to be more closely related to SystemJS then I expected as there's even references to `System.register()` calls inside the compiled `.js` files. So, it'll probably take more digging and debugging and probably won't make this sprint anymore for me. ;-) 

Thanks for the excellent support so far, the original seems to have been fixed.

**Comment by monounity** [comment] 2016-11-25 03:27
If you're referring to the `System.register()`wrapper generated by the Typescript compiler it shouldn't be a problem, you can have `"module": "system"` in your project tsconfig and override it in the Karma config with `"module": "commonjs"`:

```javascript
karmaTypescriptConfig: {
    tsconfig: "./tsconfig.json", // "module": "system"
    compilerOptions: {
        module: "commonjs" // overrides tsconfig
    }
}
```

Anyhow, I'm closing this, thanks for the detective work 😃

**Closed by monounity** 2016-11-25 03:27 UTC
Labels: bug

**Comment by honpery** [comment] 2017-02-07 16:05
Maybe some dependencies not install.for exmaple ```rxjs```.

**Comment by Fulminant** [comment] 2017-02-15 10:40
@honpery thx, you save'd my time

**Comment by nhantdn** [comment] 2017-03-01 03:39
Thank you @honpery!
