### ISSUE TITLE
Loading the SystemJS vs. CommonJS style is causing issues with momentJS

### ISSUE THREAD

**Issue by Bjeaurn** [monounity/karma-typescript#42] opened 2016-12-01 15:18 UTC
Hi, we're using Moment in a project. 

If we want it to not throw errors  in our application, we use `import moment from 'moment'` and be done with it. 

This will cause errors on the karma-typescript runner with errors like:
`search/search.component.ts(5,8): error TS1192: Module ''moment'' has no default export.`

When we change it to `import * as moment from 'moment'`, suddenly all tests run but the application throws errors when we try to use anything related with moment. Basically saying it cannot be found and it doesn't have any exported members.

I've been tinkering around with the `karma.conf.js` to try and instruct the Karma-Typescript part to handle `import moment from 'moment'` the same way the SystemJS is doing right now, but up until no luck.

Any suggestions?

```
module.exports = function (config) {
  config.set({

    frameworks: ["jasmine", "karma-typescript"],
    logLevel: config.LOG_INFO,

    files: [
      {pattern: 'app/assets/base.spec.ts'},
      {pattern: "app/assets/**/*.ts"}
    ],

    exclude: [
      "node_modules",
      "target/node-modules/webjars/",
      "node-modules"
    ],

    map: [
      {'moment': 'node_modules/moment/moment.js' }
    ],


    preprocessors: {
      "app/assets/**/*.ts": ["karma-typescript"]
    },

    exclude: [
      'app/assets/main.ts'
    ],

    reporters: ["progress", "karma-typescript"],

    karmaTypescriptConfig: {
      tsconfig: './tsconfig.json',
      compilerOptions: {
        inlineSourceMap: true,
        module: "commonjs" // overrides tsconfig
      },
      exclude: ["broken"],
      bundlerOptions: {
        ignoredModuleNames: ["react/addons"],
      },
      disableCodeCoverageInstrumentation: false,
      excludeFromCoverage: /\.(d|spec|test)\.ts/,
      remapOptions: {
        warn: function(message){
          console.log(message);
        }
      },
      reports:
      {
        "html": "coverage",
        "text-summary": ""
      },
      transformPath: function(filepath) {
        return filepath.replace(/\.(ts|tsx)$/, ".js");
      }
    },

    coverageReporter: {
      type : 'html',
      dir : 'coverage/'
    },

    browsers: ["Chrome"]
  });
};
```

**Comment by monounity** [comment] 2016-12-05 16:00
Hey @Bjeaurn, it looks like you need to set `allowSyntheticDefaultImports` to true in your tsconfig to make Typescript stop complaining about `no default export`. I need to add support for default exports in the bundler to make this work, I'll keep you posted!

**Comment by monounity** [comment] 2016-12-06 04:56
@Bjeaurn, does it work if with the latest from main now?

**Comment by Bjeaurn** [comment] 2016-12-06 07:01
Hi @monounity, thanks again for the quick support!

I've tried your first suggestion without upgrading, gotten a step further but still failed on an `undefined error`, something with `moment_default` not being a function. After upgrading to master, I've ran into new issues; missing certain typings. 
In our projects we do use typings, but not by installing them using the `typings` command. This may cause some issues in the future, but seems unrelated to the original issue at hand.

**Comment by monounity** [comment] 2016-12-07 05:41
I can reproduce this error with, for example, `import "../foo/bar-typings";`, do you have something similar in your code, ie do you `import` or `require` typings files?

**Comment by Bjeaurn** [comment] 2016-12-07 06:34
Not that I can recall in the actual project code. But there may be a reference somewhere in a module we use. I'll have a look at it.

**Comment by monounity** [comment] 2016-12-08 15:09
Ah, in that case you need to bundle typings files as well, I'll take a look and see if I can fix this!

**Comment by monounity** [comment] 2016-12-11 04:52
This was one tough nut to crack... I can reproduce the error by importing a class from a `.d.ts` file but after that I'm having a hard time wrapping my head around this. The Typescript compiler never transpiles typings files, so I get have no javascript output I can put into the bundle. I also can't serve the typings file directly to the browser because it's not valid javascript, it's still Typescript...

Do you have an example of a class loaded from a typings file? Is it an ES6 class...?

**Comment by erikbarke** [comment] 2016-12-18 11:13
@Bjeaurn, can I close this issue?

**Comment by Bjeaurn** [comment] 2016-12-19 07:16
Hi @monounity 

Excuse the delay, we've been busy with a release coming up. 

```
import {Observable} from 'rxjs/Observable'
export type JobName = "ExampleJob"
export type RepeatSchedule = "EveryDay"

export interface Schedule {
  timeOfDay: string
  repeat: RepeatSchedule
}

export interface Job {
  name: JobName,
  schedule: Schedule
}

export interface JobDescription {
  name: JobName,
  schedule: Schedule,
  nextRun: string,
  isScheduled: boolean,
  isRunning: boolean,
  result?: Observable<string> | string
  running?: Observable<number> | number
}

```

This is just one random .d.ts files in our project. We have several files for different modules. I think most of them use all the parts that are in this example, like ES6 imports to define types and things like that.

Would that help with the debugging, or is there something deeper to this problem than just importing `moment`?

**Comment by monounity** [comment] 2016-12-19 07:54
Aha, back to open!

**Comment by Bjeaurn** [comment] 2016-12-19 13:22
I also see some errors in the logs. It's referencing to `{ Error: ENOENT: no such file or directory, open 'importeren/incasso.response'`
followed by a useless stacktrace, cause it's all being called by fs.js, bundler.js, lodash.debounce and so on. So I can't see which file is requiring `incasso.response.d.ts` but it seems like the `.d.ts` seems to be causing issues here when they're used in imports.

**Comment by erikbarke** [comment] 2016-12-22 04:47
Does it work if you try the latest from the 2.1.6 branch, `npm install https://github.com/monounity/karma-typescript.git#2.1.6`?

**Comment by Bjeaurn** [comment] 2016-12-22 07:42
Hi @erikbarke.

Yes, it seems to compile again. It's also giving me most of the coverage. Still getting an error, which seems to be `.map` related.

`22 12 2016 08:33:06.702:ERROR [karma]: Error: Unable to find entry for [app/assets/app/app.component.ts]`

Other then that it runs now, so I hope this is stable. I think the issue I'm having right now is not necessarily related to the original cause of this issue, so I think we can consider this one fixed and closed.

**Comment by erikbarke** [comment] 2016-12-22 08:09
Ok, closing!

**Closed by erikbarke** 2016-12-22 08:09 UTC
Labels: bug, question
