### ISSUE TITLE
Issue Importing External Modules

### ISSUE THREAD

**Issue by archy-bold** [monounity/karma-typescript#46] opened 2016-12-12 16:28 UTC
Hi there. I've had some issues getting this set up with my project. I've seen similar issues to the one I'm having but none of the suggestions seem to work for me.

Here's the error I'm getting:

```
12 12 2016 16:17:43.442:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.1.4
12 12 2016 16:17:48.493:INFO [compiler.karma-typescript]: Compiled 19 files in 4392 ms.
12 12 2016 16:17:50.662:INFO [builtin-bundler.karma-typescript]: Bundled imports for 18 file(s) in 1644 ms.
12 12 2016 16:17:50.993:WARN [karma]: No captured browser, open http://localhost:9876/
12 12 2016 16:17:51.003:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
12 12 2016 16:17:51.004:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
12 12 2016 16:17:51.041:INFO [launcher]: Starting browser PhantomJS
12 12 2016 16:17:51.487:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket /#43zUcKqnejEGdiWSAAAA with id 4536780
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  Error: Could not find module 
  
  './splice' from
  
  '/var/www/front-end/node_modules/redux-form/lib/structure/plain' using paths
  
  [./splice]
  [/var/www/front-end/node_modules/redux-form/lib/structure/splice]
  [/var/www/front-end/node_modules/redux-form/lib/structure/splice.js]
  [/var/www/front-end/node_modules/redux-form/lib/structure/spliceindex.js]
  [/var/www/front-end/node_modules/redux-form/lib/structure/splice/index.js]
  
  at node_modules/karma-typescript/lib/bundlers/builtin/commonjs.js:51
```

I was including chai for `expect()` and that was giving similar issues, so I removed that and started getting the above.

Here's my `tsconfig.json`:

```
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "commonjs",
        "target": "es5",
        "jsx": "react",
        "baseUrl": ".",
        "typeRoots": ["./node_modules/@types"],
        "paths": {
            "*": ["src/typings/"]
        }
    },
    "filesGlob": [
        "src/**/*.ts",
        "src/**/*.tsx",
        "src/*.ts",
        "src/*.tsx"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

And my `karma.conf.js`:

```
var webpackConfig = require("./webpack.config.js");

module.exports = function (config) {
    config.set({
        basePath: "",
        frameworks: [
            "mocha",
            "chai",
            "sinon",
            "phantomjs-shim",
            "karma-typescript"
        ],

        files: [
            "src/**/*.ts",
            "src/**/*.tsx"
        ],
        exclude: [
        ],

        preprocessors: {
            "src/**/*.{ts,tsx}": ["karma-typescript"]
        },

        karmaTypescriptConfig: {
            tsconfig: "./tsconfig.json",
            excludeFromCoverage: /(d|spec|test)\.ts/
        },

        reporters: ["progress", "karma-typescript"],

        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ["PhantomJS"],
        singleRun: false,
        concurrency: Infinity
    });
}
```

I'm using node version 6.9.1.

Thanks!

**Comment by archy-bold** [comment] 2016-12-12 16:34
I tried changing the target of the `files` in the `karma.conf.js` file so I was targeting a relatively simple directory of the project and I got a similar error when trying to include one of my files from a relative path:

```
  Error: Could not find module 
  
  '../../constants/actionTypes' from
  
  '/var/www/front-end/src/actions/auth/index.js' using paths
  
  [../../constants/actionTypes]
  [/var/www/front-end/src/constants/actionTypes]
  [/var/www/front-end/src/constants/actionTypes.js]
  [/var/www/front-end/src/constants/actionTypesindex.js]
  [/var/www/front-end/src/constants/actionTypes/index.js]
  
  at node_modules/karma-typescript/lib/bundlers/builtin/commonjs.js:51
```

The file exists, though is called `/var/www/front-end/src/constants/actionTypes.ts` rather than `actionTypes.js`.

Is there something with relative paths that I'm missing? This is on a Ubuntu virtual machine.

**Comment by monounity** [comment] 2016-12-12 17:16
Hey @archy-bold, does it work if you try the latest from master, ie `npm install https://github.com/monounity/karma-typescript`? If not, I'll take look and see if I can reproduce the error with `redux-form`!

**Comment by archy-bold** [comment] 2016-12-12 17:29
Thanks for the speedy response. Got a different error now.

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: Object.isExtensible can only be called on Objects.
  at node_modules/karma-typescript/lib/bundlers/builtin/commonjs.js:20
```

**Comment by monounity** [comment] 2016-12-12 17:30
Ah, that's been fixed as well but I haven't commited it yet, I'll do that first thing tomorrow!

**Comment by archy-bold** [comment] 2016-12-12 17:38
Ah cool, bleeding edge!

This isn't an ES5/ES6 issue then? I was in the process of adding es6-shim to the project.

**Comment by monounity** [comment] 2016-12-13 05:38
Does it work if you try the latest from main now?

**Comment by archy-bold** [comment] 2016-12-13 09:42
Now getting the following error:

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: undefined is not an object (evaluating 'module.exports.default')
  at node_modules/karma-typescript/lib/bundlers/builtin/commonjs.js:20
```

**Comment by archy-bold** [comment] 2016-12-13 10:15
I've been looking into this a little myself and after correcting that error, I started getting errors in my application. For example, the following:

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: Object is not a function (evaluating 'actionCreatorFactory.default()')
  at src/actions/auth/index.js:1:133 <- src/actions/auth/index.js:21
```

Which refers to a line where I'm calling the default function of a module ['redux-typescript-actions'](https://github.com/aikoven/redux-typescript-actions):

```javascript
const actionCreator = actionCreatorFactory.default();
```

The default export for this module is a function:
```javascript
export default function actionCreatorFactory(prefix?: string, defaultIsError?: (payload: any) => boolean): ActionCreatorFactory;
```

Is this a PhantomJS issue?

**Comment by monounity** [comment] 2016-12-13 18:19
Awesome, I would love a pull request with your fix!

I don't think it's a PhantomJS issue, I've tried importing `redux-typescript-actions` and it works for me. The only difference is the documentation says `actionCreatorFactory();` instead of`actionCreatorFactory.default();`.

**Comment by monounity** [comment] 2016-12-15 05:46
Hey @archy-bold, I've added a fix for empty module.exports!

**Comment by erikbarke** [comment] 2016-12-18 11:14
@archy-bold, does it work for you now, can I close this issue?

**Closed** 2016-12-19 03:14 UTC
Labels: bug
